[package]
name = "automatic"
version = "0.1.0"
authors = ["ksh <kei.shirakizawa@gmail.com>"]

[dependencies]
clap = "2.32.0"
env_logger = "0.5.13"
failure = "0.1.1"
log = "0.4.0"
varisat = { "path" = "../../../rust_projects/varisat/varisat" }