[package]
name = "automatic"
version = "0.1.0"
authors = ["Kei Shirakizawa <kei.shirakizawa@gmail.com>"]

[dependencies]
env_logger = "0.5.13"
itertools = "0.8.0"
log = "0.4.0"
serde = "1.0.83"
serde_derive = "1.0.83"
ron = "0.4.0"
varisat = { git = "https://gitlab.com/jix/varisat.git", branch = "dev" }
